{% set name = "signal_processing_algorithms" %}
{% set version = "2.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 90275a0f315eebba857b6a8e5e13d997d3b285c4d9ca1cfbce985f8026c90e8c

build:
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - wheel
    - poetry-core
  run:
    - python >=3.8
    - more-itertools >=8.2.0,<9.0.0
    - setuptools >=65.5.1,<66.0.0
    - scipy >=1.8.1,<2.0.0
    - structlog >=19.1.0,<20.0.0
    - typing-extensions >=4.5.0,<5.0.0
    - pyyaml >=6.0.0,<7.0.0
    - gevent >=23.9.1,<24.0.0
    - typed-ast >=1.5.0,<2.0.0
    - numpy >=1.24.4,<2.0.0

test:
  imports:
    - signal_processing_algorithms
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mongodb/signal-processing-algorithms
  summary: Signal Processing Algorithms from MongoDB
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - boldorider4
